/// <reference types="@wix/sled-test-runner" />
import type { Page } from 'puppeteer';

describe('Contacts experiment', () => {
  let _page: Page;

  async function setup() {
    const { page } = await sled.newPage({
      authType: 'free-user',
    });

    _page = page;
  }

  it('should show a list of contacts', async () => {
    await setup();
    await _page.goto(require('../target/module-sled.merged.json').sledUrl);
    await _page.waitForSelector('[data-hook="app-title"]');
    const data = await _page.$eval(
      '[data-hook="app-title"]',
      (d) => d.textContent,
    );
    expect(data).toEqual('This project was generated by yoshi!');
  });
});
